kind: Template
apiVersion: v1
metadata:
  name: mattermost-rss-integration
  creationTimestamp: null
  annotations:
    openshift.io/display-name: "Mattermost rss integration"
    description: "Template to provision a Mattermost rss integration instance."
objects: 
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      service: mattermost-rss-integration
    name: mattermost-rss-integration
  spec:
    replicas: 1
    selector:
      service: mattermost-rss-integration
    strategy:
      resources:
        requests:
          cpu: 20m
          memory: 50Mi
        limits:
          cpu: 200m
          memory: 500Mi
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: mattermost-rss-integration
      spec:
        containers:
        - name: mattermost-rss-integration
          image: registry.centos.org/mattermost/mattermost-rss-integration:${IMAGE_TAG_VERSION}
          imagePullPolicy: Always
          env:
          - name: "MATTERMOST_HOOK_URL"
            valueFrom:
              secretKeyRef:
                name: mattermost-rss-config
                key: mattermosturl
          - name: "MATTERMOST_CHANNEL"
            valueFrom:
              secretKeyRef:
                name: mattermost-rss-config
                key: channel
          - name: "MATTERMOST_CMD_TOKEN"
          - name: RSS_FEED_openshiftio
            valueFrom:
              secretKeyRef:
                name: mattermost-rss-config
                key: feedurl1
          - name: RSS_FEED_analytics
            valueFrom:
              secretKeyRef:
                name: mattermost-rss-config
                key: feedurl2
          - name: RSS_FEED_launchpad
            valueFrom:
              secretKeyRef:
                name: mattermost-rss-config
                key: feedurl3
          - name: RSS_SHOW_DESCR
            value: 'False'
          - name: RSS_SILENT_MODE
            value: 'False'
          - name: RSS_SHOW_TITLE
            value: 'False'
          - name: RSS_DELAY_PULL
            value: '10'
  test: false
  triggers:
    - type: ConfigChange
parameters:
- name: IMAGE_TAG_VERSION
  value: "8e189eb"
- name: IMAGE_TAG
